### ISSUE TITLE
ejabberd PR

### ISSUE THREAD

**Issue by Neustradamus** [ethoms/raspi-hacks#1]
Hello Euan,

Sorry for this place but after some months, an email, I contact you again here about ejabberd.

Can you look your PR? (PR 2344)
Can you sign the CLA?
Update your code to last ejabberd version?

Thanks in advance.

Regards,

Neustradamus

**Comment by Neustradamus** [comment]
@ethoms: I am very interesting in your PR...
Can you sign the ProcessOne CLA?
Without "Add multi-domain support (and flexibility) to LDAP shared roster" will be never merged...

**Comment by ethoms** [comment]
Sorry for late reply. I had forgotten about that PR a while ago. I will help get it merged as soon as I have time to make sure the code still works on a recent ejabberd version. Please continue converstaion on the original PR, I left a couple messages there.

**Comment by ethoms** [comment]
Closing issue, as not related to this project.

**Comment by Neustradamus** [comment]
@ethoms: Thanks for your comeback in the ejabberd repository :)

PS: Can you remove all my issues? It is not needed and better ^^
My only goal was to have an answer from you.
Thanks :)
